client_config_backend: settings
client_config:
  client_id: 882696709444-pq9m9mdptot1tbpdeve5hf24cvijq7g7.apps.googleusercontent.com
  client_secret: GAEJQeZnoYekHW1mgaonfdR-

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install