"""new fields in user model

Revision ID: 56899baf8b98
Revises: b316f4a8928d
Create Date: 2018-09-01 14:05:05.171379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56899baf8b98'
down_revision = 'b316f4a8928d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('facebook', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('instagram', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('posted', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('twitter', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_column('post', 'twitter')
    op.drop_column('post', 'posted')
    op.drop_column('post', 'instagram')
    op.drop_column('post', 'facebook')
    # ### end Alembic commands ###
